#ifndef COMMON_H
#define COMMON_H

#include <stdbool.h>

#define GAMEPLAY_WIDTH 1024
#define GAMEPLAY_HEIGHT 896

#define MAP_X_OFFSET (GAMEPLAY_WIDTH / 2.0f - TILE_SIZE * GRID_WIDTH / 2.0f)
#define MAP_Y_OFFSET                                                           \
  (GAMEPLAY_HEIGHT - GRID_HEIGHT * TILE_SIZE + TILE_SIZE / 2.0f)

#define TILE_SIZE 64.0f
#define GRID_WIDTH 15
#define GRID_HEIGHT 13
#define GRID_SIZE (GRID_WIDTH * GRID_HEIGHT)

#define MAX_PLAYERS 4
#define MAX_PLAYER_LIVES 5
#define MAX_PLAYER_SPEED 5.0f * 60.0f
#define MAX_PLAYER_BOMBS 5

#define PLAYER_INVENCIBILITY_TIME 7.5f

#define CLEAN_MODE false

#define PLAYER_DEFAULT_LIVES 3
#define PLAYER_DEFAULT_SPEED 3.0f * 60.0f

#define DEFAULT_BOMB_RADIUS 1
#define DEFAULT_EXPLOSION_LIFETIME 0.6f
#define DEFAULT_BOMBS 1
#define MAX_BOMB_RADIUS 10

#define MAP_CHANGE_INTERVAL 90.0f
#define PROBABILITY_SPAWN_TILE_BRICK_ON_MAP 30

#define BOMB_PROBABILITY 50.0f
#define ENEMY_PROBABILITY 50.0f

#define POWER_UP_PROBABILITY 10
#define POWER_UP_SPEED_INCREASE (MAX_PLAYER_SPEED * 0.05)
#define POWER_UP_MAP_LIMIT 6
#define POWER_UP_TIMEOUT 60.0f

#define ENTITY_COLISION_TOLERANCE 16.0f

#define ENEMY_MAP_LIMIT 6

#define RANDOM_EVENT_INTERVAL 5.0f
#define RANDOM_EVENT_INTERVAL_DECREASE 0.25f
#define RANDOM_BOMB_INITIAL_RADIUS 1
#define RANDOM_BOMB_RADIUS_INCREASE 1
#define RANDOM_BOMB_QUANTITY_INCREASE 1
#define RANDOM_BOMB_INITIAL_QUANTITY 3
#define RANDOM_BOMB_MAP_QUANTITY_INCREASE 3

#define RANDOM_ENEMY_QUANTITY_INCREASE 1
#define RANDOM_ENEMY_INITIAL_QUANTITY 3
#define RANDOM_ENEMY_MAP_QUANTITY_INCREASE 3

#define MACHINE_SPAWN_ANIMATION_TIME 1.0f
#define MACHINE_SPAWN_ANIMATION_TICKS 25

#endif
