#ifndef COMMON_H
#define COMMON_H

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768

#define TILE_SIZE 48
#define GRID_WIDTH 15
#define GRID_HEIGHT 13
#define GRID_SIZE (GRID_WIDTH * GRID_HEIGHT)

#define MAP_X_OFFSET (SCREEN_WIDTH / 2 - TILE_SIZE * GRID_WIDTH / 2)
#define MAP_Y_OFFSET (SCREEN_HEIGHT / 2 - TILE_SIZE * GRID_HEIGHT / 2)

#define MAX_PLAYERS 1

#endif
